import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Weather application',
  description: 'Weather application that uses weatherapi. Generated by create next app',
  author:'karl robeck alferez'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
